strictness: high
test-warnings: true
doc-warnings: false

pylint:
  disable:
    - too-many-instance-attributes
    - import-outside-toplevel
    - consider-using-generator

ignore-paths:
  - flamapy/metamodels/smt_metamodel/transformations/

mccabe:
  run: true